# Schema for the configuration files of the Bootstrap Barrio Subtheme.

acephap.settings:
  type: theme_settings
  label: 'Acephap theme settings'
  mapping:
    acephap_sidebar_position:
      type: text
      label: 'Sidebar Position'
    acephap_content_offset:
      type: integer
      label: 'Offset'
    acephap_sidebar_first_width:
      type: integer
      label: 'Width'
    acephap_sidebar_first_offset:
      type: integer
      label: 'Offset'
    acephap_sidebar_second_width:
      type: integer
      label: 'Width'
    acephap_sidebar_second_offset:
      type: integer
      label: 'Offset'
    acephap_footer_layout:
      type: text
      label: 'Layout'
    acephap_fluid_container:
      type: integer
      label: 'Enabled'
    acephap_button_size:
      type: text
      label: 'Size'
    acephap_button_outline:
      type: integer
      label: 'Button outline'
    acephap_navbar_top_position:
      type: text
      label: 'Position'
    acephap_navbar_top_color:
      type: integer
      label: 'Color'
    acephap_navbar_top_background:
      type: text
      label: 'Background'
    acephap_navbar_position:
      type: text
      label: 'Position'
    acephap_navbar_color:
      type: integer
      label: 'Color'
    acephap_navbar_background:
      type: text
      label: 'Background'
    acephap_anchors_fix:
      type: integer
      label: 'Enabled'
    acephap_anchors_smooth_scrolling:
      type: integer
      label: 'Enabled'
    acephap_forms_required_has_error:
      type: integer
      label: 'Enabled'
    acephap_forms_has_error_value_toggle:
      type: integer
      label: 'Enabled'
    acephap_forms_smart_descriptions:
      type: integer
      label: 'Enabled'
    acephap_forms_smart_descriptions_limit:
      type: integer
      label: 'Limit'
    acephap_forms_smart_descriptions_allowed_tags:
      type: text
      label: 'Allowed tags'
    acephap_popover_enabled:
      type: integer
      label: 'Enabled'
    acephap_popover_animation:
      type: integer
      label: 'Enabled'
    acephap_popover_html:
      type: integer
      label: 'Enabled'
    acephap_popover_placement:
      type: text
      label: 'Placement'
    acephap_popover_selector:
      type: text
      label: 'Selector'
    acephap_popover_trigger_autoclose:
      type: integer
      label: 'Enabled'
    acephap_popover_delay:
      type: integer
      label: 'Enabled'
    acephap_popover_trigger:
      type: mapping
      mapping:
        hover:
          type: integer
          label: 'Hover'
    acephap_tooltip_enabled:
      type: integer
      label: 'Enabled'
    acephap_tooltip_descriptions:
      type: integer
      label: 'Enabled'
    acephap_tooltip_descriptions_length:
      type: integer
      label: 'Length'
    acephap_tooltip_animation:
      type: integer
      label: 'Enabled'
    acephap_tooltip_html:
      type: integer
      label: 'Length'
    acephap_tooltip_delay:
      type: integer
      label: 'Enabled'
    acephap_popover_title:
      type: text
      label: 'Title'
    acephap_popover_content:
      type: text
      label: 'Content'
    acephap_tooltip_placement:
      type: text
      label: 'Placement'
    acephap_tooltip_container:
      type: text
      label: 'Container'
    acephap_tooltip_selector:
      type: text
      label: 'Selector'
    acephap_tooltip_trigger:
      type: mapping
      mapping:
        hover:
          type: text
          label: 'Hover'
    acephap_popover_container:
      type: text
      label: 'Container'